// Generated by CoffeeScript 1.6.3
window.addEventListener("load", function(e) {
  console.debug("Page loaded.");
  if (window.top === window) {
    console.debug("Page processed.");
    return safari.self.tab.dispatchMessage("page-loaded", {
      body: document.body.innerText,
      title: document.title,
      url: document.location.toString()
    });
  }
}, false);
